//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using interopservices = System.Runtime.InteropServices;
#if NET_CF20


[assembly: ServiceDeclaration(DssServiceDeclaration.Proxy, SourceAssemblyKey="cf.wiimote.y2007.m06, version=1.2.0.0, culture=neutral, publickeytoken=5efc51320be57" +
    "81c")]

#else


[assembly: ServiceDeclaration(DssServiceDeclaration.Proxy, SourceAssemblyKey="wiimote.y2007.m06, version=1.2.0.0, culture=neutral, publickeytoken=5efc51320be57" +
    "81c")]

#endif
[assembly: System.Security.SecurityTransparentAttribute()]
[assembly: System.Security.AllowPartiallyTrustedCallersAttribute()]
[assembly: interopservices.ComVisible(true)]


